{"name": "После оформления заказа его номер появляется в разделе \"В работе\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_order_feed.TestOrderFeed object at 0x000002463628B230>, login = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"d1d260b7-9ac0-49e6-bbb3-2f84d1be30c7\")>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"d1d260b7-9ac0-49e6-bbb3-2f84d1be30c7\")>\n\n    @allure.title('После оформления заказа его номер появляется в разделе \"В работе\"')\n    def test_order_number_appears_in_work(self, login, driver):\n        driver = login\n        feed_page = FeedPage(driver)\n        main_page = MainPage(driver)\n    \n        # костыль для прогрузки страницы, без неё не нажимется кнопки (чтобы не использовать sleep)\n        main_page.check_display_bun()\n        number_order = main_page.create_order()\n        main_page.click_to_button_order_history()\n>       numbers_order_in_progress = feed_page.get_updated_order_number_in_list_in_progress()\n\ntests\\test_order_feed.py:82: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\feed_page.py:35: in get_updated_order_number_in_list_in_progress\n    return self.get_updated_text_from_element(FeedPageLocators.NUMBER_ORDER_IN_PROGRESS)\npages\\base_page.py:34: in get_updated_text_from_element\n    element = wait.until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"d1d260b7-9ac0-49e6-bbb3-2f84d1be30c7\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x000002463670ADE0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Отображается ингридиент \"Булка\"", "status": "passed", "start": 1715253419053, "stop": 1715253419566}, {"name": "Создание заказа", "status": "passed", "steps": [{"name": "Перетаскивание ингредиента в правую часть экрана", "status": "passed", "start": 1715253419566, "stop": 1715253420143}, {"name": "Нажать на кнопку \"Оформить заказ\"", "status": "passed", "start": 1715253420144, "stop": 1715253420414}, {"name": "Получить номер заказа", "status": "passed", "start": 1715253420414, "stop": 1715253423996}, {"name": "Закрыть всплывающее окно с номером заказа", "status": "passed", "start": 1715253423996, "stop": 1715253424285}], "start": 1715253419566, "stop": 1715253424285}, {"name": "Нажать на кнопку \"Лента заказов\"", "status": "passed", "start": 1715253424285, "stop": 1715253424583}, {"name": "Получить номер заказа, как он появится в списке", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_Victor_Korol_6\\Diplom_3\\pages\\feed_page.py\", line 35, in get_updated_order_number_in_list_in_progress\n    return self.get_updated_text_from_element(FeedPageLocators.NUMBER_ORDER_IN_PROGRESS)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\Diplom_Victor_Korol_6\\Diplom_3\\pages\\base_page.py\", line 34, in get_updated_text_from_element\n    element = wait.until(EC.visibility_of_element_located(locator))\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1715253424583, "stop": 1715253435127}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1715253419053, "stop": 1715253435127, "uuid": "d0d3f3a5-7bfb-4a21-8823-3eb4172e9057", "historyId": "95d0e12b607689c2b5c48e8f792306f7", "testCaseId": "a1021e6017f4b231e113f79c1b83627f", "fullName": "tests.test_order_feed.TestOrderFeed#test_order_number_appears_in_work", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed"}, {"name": "subSuite", "value": "TestOrderFeed"}, {"name": "host", "value": "WIN-081B0PRJBJT"}, {"name": "thread", "value": "8728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed"}]}